# Generated by Django 4.2.4 on 2023-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=500)),
                ('project_lead', models.CharField(max_length=50)),
                ('programming_langauge', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], max_length=50)),
                ('project_start_date', models.DateTimeField()),
                ('project_delivery_date', models.DateTimeField()),
            ],
        ),
    ]
